# Generated by Django 5.2.3 on 2025-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text="Optional description of what this skill does or how it's used"),
        ),
    ]
