# Generated by Django 4.2.23 on 2025-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='actions',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of required mechanical actions for this prompt'),
        ),
    ]
